variables:
  TF_VAR_service_name: "safina-app-service-devint-$CI_PIPELINE_IID"

include:
  - component: &core-yaml-tpl $CI_SERVER_FQDN/ciorg/community/cmf/pipeline/core-yaml/include@2.4.2
    inputs: &core-yaml-input
      deploy_stages: ''
      feature_deploy_stages: ''
      manual_promote_to_stage: 'no' # auto promote to stage
      manual_promote_to_prod: 'no' # auto promte to prod
      final_deploy_behavior: on_success # default manual
      is_http_service: false
      build_and_test_image_version: '8.2'
      build_and_test_image: php
      service_language: golang # Ignore this one. Used only to satisfy the logic checks
      include_build_job: false
      deploy_tooling: 'terraform'
      terraform_dir: 'terraform'
      unit_tests_script:
        - echo "Unit test successful"
      smoke_tests_script:
        - echo "Smoke test successful"
      integration_tests_script:
        - echo "Integration test successful"
      container_build_dockerfile_path: "./Dockerfile"
      feature_deploy_env: devint
      state_type: "s3_bypath"

  #   rules:
  #     - if: >-
  #         $CI_COMMIT_TAG !~ /.*-prod/i

  # - component: *core-yaml-tpl
  #   inputs:
  #     <<: *core-yaml-input
  #     deploy_stages: blue-green,canary
  #     canary_deploy_behavior: on_success
  #     final_deploy_behavior: manual
  #     feature_deploy_env: prod
  #   rules:
  #     - if: >-
  #         $CI_COMMIT_TAG =~ /.*-prod/i

      
