name: "safina-ci4"

services:
  php-apache:
    build: .
    container_name: "${COMPOSE_PROJECT_NAME}-php-nginx"
    #volumes:
    #- ./:/var/www/html
    ports:
      - "8080:8080"
    environment:
      NGINX_WEBROOT: /var/www/html/public
      #APACHE_DOCUMENT_ROOT: /var/www/html
      SSL_MODE: "off"
      PHP_DISPLAY_ERRORS: 1
    networks:
      - default

networks:
  default:
    name: localnetwork
    external: true

