FROM serversideup/php:8.3-fpm-apache

# --- Environment Variables ---
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
ENV SSL_MODE=off
ENV PHP_DISPLAY_ERRORS=1
# Overwritten in Docker Compose file
ENV DOCKER_COMPOSE_USAGE=0 
# --- System Setup (Root User) ---
USER root

# Install necessary PHP extensions AND gettext for envsubst
RUN apt-get update && \
    apt-get install -y gettext-base git dos2unix && \
    install-php-extensions bcmath intl mysqli && \
    mkdir -p /var/www/html/ && \
    chown -R www-data:www-data /var/www/html/ && \
    rm -rf /var/lib/apt/lists/* # Clean up apt cache to keep image small

# This container ENTRYPOINT as per serversiderup/php
# COPY  --chown=root:root ./entrypoint.d/envsubst.sh /etc/entrypoint.d/

# RUN dos2unix /etc/entrypoint.d/envsubst.sh && \ 
#     chmod +x /etc/entrypoint.d/envsubst.sh

USER www-data

WORKDIR /var/www/html/

# COPY --chown=www-data:www-data composer.json composer.lock ./
# RUN composer install --no-dev --optimize-autoloader

# COPY --chown=www-data:www-data . .
# RUN ln -s /var/www/html/public  /var/www/html/public/devint
# RUN ln -s /var/www/html/public /var/www/html/public/stage
