server {
        listen 8080;
        listen [::]:8080;

        server_name _;

        root /var/www/devint/public;
        index index.php index.html index.htm;

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        }
        error_page 404 /index.php;

        location ~ /\. {
                deny all;
        }
}